[[plugins]]
repo = 'shougo/denite.nvim'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin' [[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'thinca/vim-visualstar'
[[plugins]]
repo = 'kien/ctrlp.vim'
[[plugins]]
repo = 'mattn/emmet-vim'
[[plugins]]
repo = 'Shougo/neocomplete.vim'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'tomtom/tcomment_vim'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 't9md/vim-textmanip'
[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'jceb/vim-orgmode'
[[plugins]]
repo = 'tpope/vim-speeddating'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_ft = ['python']

[[plugins]]
repo = 'prabirshrestha/async.vim'
on_ft = ['python']

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = ['python']
depends = ['async.vim', 'vim-virtualenv']
hook_source = '''
source ~/.config/nvim/plugins/vim-lsp.rc.vim
'''

[[plugins]]
repo = 'ryanolsonx/vim-lsp-python'
on_ft = ['python']
depends = ['vim-lsp']
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_ft = ['python']

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
